// import { color } from "framer-motion";

export const cardData = [
    {
        id:1,
        backgroundColor: "lightyellow",
        src : '/pic-12.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$2.7" ,  
        rating :  "3.8 ",
    },
    {
        id:2,
        backgroundColor: "#C2AD44",
        src : '/Girl-pic4.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$3.0" ,  
        rating :  "4.9",
    },
    {
        id:3,
        backgroundColor: "#795c5c;;",
        src : '/Men-pic1.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$4.7" ,  
        rating :  "5.0 ",
    },
    {
        id:4,
        backgroundColor: "rgb(184, 232, 112)",
        src : '/Girl-pic8.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$5.0" ,  
        rating :  "3.0 ",
    },
    {
        id:5,
        backgroundColor: "#6CA1BE",
        src : '/Men-pic2.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$2.7" ,  
        rating :  "2.8 ",
    },
    {
        id:6,
        backgroundColor: "#69A8A8",
        src : '/Girl-pic7.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$5.9" ,  
        rating :  "4.7",
    },
    {
        id:7,
        backgroundColor: "#5873A9",
        src : '/Men-pic3.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$6.7" ,  
        rating :  "5.0 ",
    },
    {
        id:8,
        backgroundColor: "#62B57A",
        src : '/Girl-pic6.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$5.3" ,  
        rating :  "2.0 ",
    },
    {
        id:9,
        backgroundColor: "lightyellow",
        src : '/Men-pic4.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$6.7" ,  
        rating :  "5.0 ",
    },
    {
        id:10,
        backgroundColor: "#FBDBDB",
        src : '/Girl-pic5.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$5.5 " ,  
        rating :  "4.1",
    },
    {
        id:11,
        backgroundColor: "#E16E21",
        src : '/Girl-pic00.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$4.5" ,  
        rating :  "2.0 ",
    },
  
    {
        id:12,
        backgroundColor: "#CBC3C3",
        src : '/Men-pic5.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$6.0" ,  
        rating :  "5.0 ",
    },
    {
        id:13,
        backgroundColor: "#AEA5A5",
        src : '/Men-shoes1.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$2.4" ,  
        rating :  "3.7 ",
    },
   
    {
        id:14,
        backgroundColor: "#6CA1BE",
        src : '/Girl-pic3.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$4.0" ,  
        rating :  "4.7 ",
    },
    {
        id:15,
        backgroundColor: "#F6E698",
        src : '/Girl-shoes1.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$3.4" ,  
        rating :  "3.4 ",
    },
    {
        id:16,
        backgroundColor: "#9C62B5",
        src : '/Girl-pic2.png',
        heading: "Dress  often reflect cultural trends.",
        price : "$3.9" ,  
        rating :  "4.2 ",
    },
   
    
]